[package]
name = "pomotui-sync"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["std"] }
pomotui-domain = { path = "../pomotui-domain" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
uuid = { version = "1", features = ["serde", "v4"] }

[lints]
workspace = true
